function [ eta_dot ] = simReducedOrder( t, eta, k, M, m, l, ...
                                        g, k_tan,           ...
                                        b_p_c, b_p_v,       ...
                                        b_c_c, b_c_v        )
  xi = -k*eta;
  eta2 = eta(2);
  eta3 = eta(3);

  eta_dot = [   (l*(eta2 + xi))/cos(eta3)                                 ;
              - (l^2*m*xi^2*sin(eta3)                                 - ...
              - b_p_c*tanh((k_tan*l*(eta2 + xi))/cos(eta3))*cos(eta3) - ...
              - b_p_v*xi*cos(eta3) + g*l*m*cos(eta3)*sin(eta3)        + ...
              + eta2*l^2*m*xi*sin(eta3))/(l^2*m*cos(eta3))                ;
                xi                                                       ];
 