function [ eta_dot, xi ] = simReducedOrder( t, eta, k, M, m, l, ...
                                            g, k_tanh,           ...
                                            b_p_c, b_p_v,       ...
                                            b_c_c, b_c_v        )

  eta1 = eta(1);
  eta2 = eta(2);
  eta3 = eta(3);
  
  xi   = -k*eta;

  eta_dot = [   (xi*cos(eta1))/l - eta2                                  ;
                (b_p_v*xi*cos(eta1) - l*m*xi^2 - b_p_v*eta2*l          ...
              + b_p_c*l*tanh(k_tanh*xi) + l*m*xi^2*cos(eta1)^2         ...
              - g*l^2*m*sin(eta1) + eta2*l^2*m*xi*sin(eta1))/(l^3*m)     ;
                xi                                                      ];