xticks([-5*pi -4*pi -3*pi -2*pi -pi 0 pi 2*pi 3*pi 4*pi 5*pi])
xticklabels( {'$-5\pi$' '$-4\pi$' '$-3\pi$' '$-2\pi$' '$-\pi$' '$0$' ...
              '$\pi$'   '$2\pi$'  '$3\pi$'  '$4\pi$'  '$5\pi$'       } )
yticks([-5*pi -4*pi -3*pi -2*pi -pi 0 pi 2*pi 3*pi 4*pi 5*pi])
yticklabels( {'$-5\pi$' '$-4\pi$' '$-3\pi$' '$-2\pi$' '$-\pi$' '$0$' ...
              '$\pi$'   '$2\pi$'  '$3\pi$'  '$4\pi$'  '$5\pi$'       } )